### ISSUE TITLE
Transformation fails using Atom release 1.11.1

### ISSUE THREAD

**Issue by alexjota** [russlescai/atom-xsltransform#9]
Hi!
the following issue started with the latest release of Atom (1.11.1) on a Mac. I am using Saxon to perform the transformations.

Repro
1. In Atom, open an XML file
2. Run the Transform XML command from the command palette
3. Point to an XSL file
4. Get the error

Below, Atom's stack trace
hope this helps.
Thanks!

**Atom Version**: 1.11.1
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [atom-xsltransform](https://github.com/russlescai/atom-xsltransform) package, v0.8.0
### Stack Trace

Uncaught TypeError: Arguments to CompositeDisposable.add must have a .dispose() method

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:70

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:70:13)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:43:11)
    at new CompositeDisposable (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:19:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:265:29
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:388:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:372:28
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:491:20)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:434:14)
    at /Users/alejandrojezierski/.atom/packages/atom-xsltransform/lib/atom-xsltransform-view.coffee:100:18
    at ChildProcess.exithandler (child_process.js:205:7)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```
### Commands

```
     -9:05.9.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -9:03.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -9:03.2.0 atom-xsltransform:transform-xml (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -9:01.8.0 core:move-right (atom-text-editor.editor.mini.is-focused)
 42x -9:00.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -8:40.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:04.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.6.0 atom-xsltransform:transform-xml (atom-text-editor.editor)
     -0:02.9.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -0:02.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "automaticallyUpdate": false,
    "disabledPackages": [
      "atom-jshint",
      "jshint"
    ],
    "telemetryConsent": "no"
  },
  "atom-xsltransform": {
    "externalXslToolPath": "saxon -s:%XML -xsl:%XSL"
  }
}
```
### Installed Packages

``` coffee
# User
atom-xsltransform, v0.8.0 (active)
autocomplete-xml, v0.8.3 (active)
jshint, v1.8.5 (inactive)
node-debugger, v1.7.0 (active)
pretty-json, v1.6.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by russlescai** [comment]
@alexjota I tested on 1.22.1 and it works OK, are you still having issues?

**Comment by russlescai** [comment]
@alexjota if you have a chance to check, feel free to reopen and I will investigate. :)
